### ISSUE TITLE
Implement these dope design fixes

### ISSUE THREAD

**Issue by aaronhans** [openoakland/clean-water#19]
These designs are awesome: https://www.figma.com/file/zrPWQpnZyo0KI54BC1V0fc/CA-Water?node-id=0%3A1

There are a lot of accessibility fixes to be had by following these design recommendations, might want to split this up into smaller issues and addressed individually but a lot of beautiful improvements suggested here that will make the site better

**Comment by mkeisenbach** [comment]
I would like to start implementing some of the design recommendations - starting with the CSS.

**Comment by mkeisenbach** [comment]
Design fixes have been implemented.
